/*

function writeLog(log,log2){
    console.log(log);
    console.log(log2);

}
writeLog('Test message','vinh');












function writeLog(){

    var myString='';
    for (var param of arguments){
         myString += `${param} - `
    }
    console.log(myString);
}


writeLog('log 1','log 2','log 3');


--return trong ham
function cong(a,b){
    return a+b;
    //or return[a,b];
    // return a.tString() + b.Tostring();.........

}


console.log(cong(8,2));











// cac loai funcition


1.deckaration funciton: normal.có thể gọi đc trước khi đc định nghĩa
2.expreesion funcition:


var showMessage2 =function(){

}


var setTimeout((function){

});


var myOject ={
    myFunction: function(){
        
    }
}



3.arrow funcition











*/






















