/*
--Math.Pi: so pi
--Math.round():lam tron so
--Math.abs(). gia tri tuyet doi
--Math.ceil()// lam tron tren keer ca vs so nho nhat
--Math.floor()// lam tron duowi
--Math.random()// tra ve day so thap phan nho hon 1 vd: 0.2566
--Math.min();
--Math.max();





*/ 





// vd tao  so ngau nhien tu 0 den 9

var random = Math.floor(Math.random()*5);


var bonus=[
    '10 coin',
    '20 coin',
    '30 coin',
    '40 coin',
    '50 coin'

]

console.log(bonus[random]);



console.log(Math.max(100,50,-12));
